import Head from "next/head";
import {getTopWriters, getTopBlogs} from "../lib/apis";
import {Writer, Blog} from "../lib/interfaces";
import {Container} from "@mui/material";
import HomeHero from "../components/HomeHero";
import TopBlogs from "../components/TopBlogs";
import TopWriters from "../components/TopWriters";

const Home = ({topWriters, topBlogs}: any) => {
  // console.log("TOP WRITERS", topWriters);
  return (
    <Container maxWidth={false} disableGutters>
      <Head>
        <title>{process.env.TITLE}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <HomeHero />
      <TopBlogs topBlogs={topBlogs} />
      <TopWriters topWriters={topWriters} />
    </Container>
  );
};

export default Home;

export async function getStaticProps() {
  const topWriters: Writer[] = await getTopWriters();
  const topBlogs: Blog[] = await getTopBlogs();
  return {
    props: {
      topWriters,
      topBlogs,
    },
    revalidate: 1,
  };
}
