import Head from "next/head";
import Site from "../layout/Site";
import {ReactElement} from "react";
import {useSelector, useDispatch} from "react-redux";
import {selectUser} from "../State/Slices/CurrentUserSlice";
import {getTopWriters, getTopBlogs} from "../lib/apis";
import {Writer, TopWriters, Blog, TopBlogs} from "../lib/interfaces";

const Home = ({topWriters}: TopWriters) => {
  // const y = topWriters;
  // console.log(y);
  const currentUser = useSelector(selectUser);
  const dispatch = useDispatch();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>Welcome to Blogtor</div>
      {/* <button onClick={() => dispatch(increment())}>Increment</button>
      <button onClick={() => dispatch(decrement())}>Decrement</button>
      <h1>The value of the counter is {count}</h1>
      <h1>The value of customKey is: {process.env.DOMAIN}</h1> */}
    </>
  );
};

Home.getLayout = function getLayout(page: ReactElement) {
  return <Site>{page}</Site>;
};

export default Home;

export async function getStaticProps() {
  const topWriters: Writer[] = await getTopWriters();
  const topBlogs: Blog[] = await getTopBlogs();
  return {
    props: {
      topWriters,
      topBlogs,
    },
  };
}


