import Head from "next/head";
import Site from "../layout/Site";
import {ReactElement} from "react";
import {useSelector, useDispatch} from "react-redux";
import {selectUser} from "../State/Slices/CurrentUserSlice";
import {getTopWriters, getTopBlogs} from "../lib/apis";
import {Writer, TopWriters, Blog, TopBlogs} from "../lib/interfaces";
import {Button, Container, Typography} from "@mui/material";
import DriveFileRenameOutlineOutlinedIcon from "@mui/icons-material/DriveFileRenameOutlineOutlined";
import Link from "next/link";

const Home = ({topWriters}: TopWriters) => {
  // const y = topWriters;
  // console.log(y);
  const currentUser = useSelector(selectUser);
  const dispatch = useDispatch();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Container
        maxWidth={false}
        disableGutters
        sx={{
          bgcolor: "primary.light",
          height: "617px",
          display: "flex",
          justifyContent: "center",
          flexDirection: "column",
          alignItems: "center",
        }}>
        <Container
          sx={{
            height: "367px",
            width: "473px",
            bgcolor: "primary.light",
            padding: "50px",
          }}>
          <Container
            sx={{
              display: "flex",
              alignItems: "center",
              gap: "7px",
              justifyContent: "center",
              mb: "32px",
            }}>
            <Typography
              variant='logo'
              sx={{display: "flex", alignItems: "center", gap: "2px"}}>
              <DriveFileRenameOutlineOutlinedIcon />
              Write On
            </Typography>
            <Typography variant='title'>Blogtor</Typography>
          </Container>
          <Container
            sx={{
              display: "flex",
              alignItems: "center",
              flexDirection: "column",
              justifyContent: "center",
              textAlign: "center",
            }}>
            <Typography variant='title' sx={{mb: "20px"}}>
              Writing on Blogtor is very simple
            </Typography>
            <Typography variant='mainText'>
              Register by one click and go to your dashboard and start posting
              your blogs!
            </Typography>
            <Typography variant='title' sx={{mt: "20px"}}>
              Rate and Comment on other blogs
            </Typography>
            <Typography variant='mainText'>
              You can read, rate and comment on other writers blogs.
            </Typography>
            <Link href={"/Register"}>
              <Button variant='outlineButtons' sx={{mt: "20px"}}>
                Join Now
              </Button>
            </Link>
          </Container>
        </Container>
      </Container>
      <Container
        maxWidth={false}
        disableGutters
        sx={{
          bgcolor: "primary.veryLight",
          height: "617px",
          display: "flex",
          justifyContent: "center",
          flexDirection: "column",
          alignItems: "center",
        }}>
        adfs
      </Container>
    </>
  );
};


export default Home;

export async function getStaticProps() {
  const topWriters: Writer[] = await getTopWriters();
  const topBlogs: Blog[] = await getTopBlogs();
  return {
    props: {
      topWriters,
      topBlogs,
    },
  };
}


