import {NextPageWithLayout} from "../_app";
import {useRef, useState} from "react";
import {postBlog} from "../../lib/apis";
import {useRouter} from "next/router";
import {Button, Container, TextField} from "@mui/material";
import TextEditor from "../../components/TextEditor";
import {toast} from "react-toastify";
import Head from "next/head";

const PostBlog: NextPageWithLayout = () => {
  const router = useRouter();
  const [bloginfo, setBloginfo] = useState({
    title: "",
    content: "",
    imgurl: "",
  });

  const editorRef = useRef(null);

  async function post() {
    const data = await postBlog(
      bloginfo.title,
      editorRef?.current?.getContent(),
      bloginfo.imgurl
    );
    if (data._id) {
      router.push(`/Blogs/${data._id}`);
      return toast.success("successgully posted");
    }
    if (data.msg === "bad request: bad inputs") return alert("ridi");
    if (data.msg === "Unathorized") return alert("badam ridi");
  }

  return (
    <>
      <Head>
        <title>{process.env.TITLE} | Post Blog</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <TextField
        placeholder='Blog title...'
        sx={{mb: "20px", width: "100%"}}
        onChange={(e) => setBloginfo({...bloginfo, title: e.target.value})}
      />
      <TextField
        placeholder='Blog image URL'
        sx={{mb: "20px", width: "100%"}}
        onChange={(e) => setBloginfo({...bloginfo, imgurl: e.target.value})}
      />
      <TextEditor initialValue={bloginfo.content} editorRef={editorRef} />
      <Button variant='normalButtons' onClick={post} sx={{mt: "20px"}}>
        Submit
      </Button>
    </>
  );
};

export default PostBlog;

